name: Deploy Django To-Do List Public

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Stop and remove old containers
        run: |
          OLD_CONTAINERS=$(docker ps -a --filter name=todolist_public --format "{{.ID}}")
          if [ -n "$OLD_CONTAINERS" ]; then
            docker stop $OLD_CONTAINERS
            docker rm $OLD_CONTAINERS
          fi
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t ghcr.io/arsank47/todolist_public:latest .
        working-directory: /home/rhodium-ubuntu/actions-runner-DjangoToDoListPublic/_work/DjangoToDoListPublic1/DjangoToDoListPublic1 # UPDATE THIS PATH

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/arsank47/todolist_public:latest

      - name: Pull Docker image from GHCR (optional)
        run: docker pull ghcr.io/arsank47/todolist_public:latest  # Optional step for verification

      - name: Run container with restart
        run: |
          docker run --name todolist_public -d --restart=always -p 8002:8002 ghcr.io/arsank47/todolist_public:latest

      - name: Show Docker containers
        run: docker ps
