name: Deploy Django To-Do List Public

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Backup Database
        run: |
          if docker ps -a | grep todolist_public; then
            echo "Backing up database from running container..."
            docker cp todolist_public:/app/todo_list/db.sqlite3 ~/persistent-storage/db.sqlite3 || echo "Backup failed!"
          else
            echo "No running container to back up from. First deployment?"
          fi

      - name: Stop and Remove Old Containers
        run: |
          OLD_CONTAINERS=$(docker ps -a --filter name=todolist_public --format "{{.ID}}")
          if [ -n "$OLD_CONTAINERS" ]; then
            docker stop $OLD_CONTAINERS
            docker rm $OLD_CONTAINERS
          fi
        continue-on-error: true

      - name: Build Docker Image
        run: docker build -t ghcr.io/arsank47/todolist_public:latest .
        working-directory: /home/rhodium-ubuntu/actions-runner-DjangoToDoListPublic/_work/DjangoToDoListPublic1/DjangoToDoListPublic1

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/arsank47/todolist_public:latest

      - name: Restore Database
        run: |
          if [ -f ~/persistent-storage/db.sqlite3 ]; then
            echo "Restoring database from persistent storage..."
          else
            echo "No database found in persistent storage; starting fresh."
          fi

      - name: Run New Container
        run: |
          docker run --name todolist_public -d --restart=always \
            -v ~/persistent-storage/db.sqlite3:/app/todo_list/db.sqlite3 \
            -p 8003:8003 ghcr.io/arsank47/todolist_public:latest
            
      - name: Apply Migrations
        run: |
          docker exec todolist_public python manage.py migrate

      - name: Show Docker Containers
        run: docker ps
